requires:
- name: "tool"
  category: "distro"
  version: ">=0"

prelude:
{{ template "distro_install_tools" (dict "Values" .Values "Packages" "curl")}}
- curl -LO https://github.com/ivandavidov/systemd-boot/releases/download/systemd-boot_{{.Values.package_version}}/systemd-boot_{{.Values.package_version}}.tar.xz
- echo "{{ ( index .Values.labels "package.checksum" ) }}  systemd-boot_{{.Values.package_version}}.tar.xz" | sha256sum -c
- mkdir -p /systemd-boot
- tar -xvf systemd-boot_{{.Values.package_version}}.tar.xz -C /systemd-boot
steps:
- mkdir -p /EFI/BOOT
- cp /systemd-boot/systemd-boot*/uefi_root/EFI/BOOT/BOOTx64.EFI /EFI/BOOT
- cp /systemd-boot/systemd-boot*/uefi_root/EFI/BOOT/BOOTIA32.EFI /EFI/BOOT
