# This spec is meant to be consumed only from a root image which ends up being used as uefi image.
# TODO: verify checksum
requires:
- name: "base"
  category: "distro"
  version: ">=0"

prelude:
{{if eq .Values.distribution "opensuse" }}
- zypper in -y wget
{{else if eq .Values.distribution "fedora" }}
- dnf install -y wget
{{end}}
- wget https://github.com/ivandavidov/systemd-boot/releases/download/systemd-boot_{{.Values.package_version}}/systemd-boot_{{.Values.package_version}}.tar.xz
- mkdir -p /systemd-boot
- tar -xvf systemd-boot_{{.Values.package_version}}.tar.xz -C /systemd-boot
steps:
- mkdir -p /EFI/BOOT
- cp /systemd-boot/systemd-boot*/uefi_root/EFI/BOOT/BOOTx64.EFI /EFI/BOOT
- cp /systemd-boot/systemd-boot*/uefi_root/EFI/BOOT/BOOTIA32.EFI /EFI/BOOT
