requires:
- name: "tool"
  category: "distro"
  version: ">=0"
env:
- GITHUB_ORG={{ ( index .Values.labels "github.owner" ) }}
- GITHUB_REPO={{ ( index .Values.labels "github.repo" ) }}

{{ if .Values.tool_image_distribution }}
{{if eq .Values.tool_image_distribution "opensuse" }}
prelude:
- zypper ar https://download.opensuse.org/repositories/security:/SELinux/openSUSE_Leap_15.3/security:SELinux.repo
- zypper --gpg-auto-import-keys in -y --allow-vendor-change --allow-downgrade container-selinux -libsemanage1

steps:
- |
    PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && \
    # the last value in the github tag(semver minor) is translated to the rpm release format for some reason so we need to transform it here (¬_¬)
    PACKAGE_VERSION="${PACKAGE_VERSION%.*}-${PACKAGE_VERSION##*.}" && \
    mkdir /tmp/rpm && \
    cd /tmp/rpm && \
    curl -L -O https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/{{ ( index .Values.labels "github.tag" ) }}/{{.Values.name}}-{{.Values.category}}-${PACKAGE_VERSION}.el7.noarch.rpm && \
    echo "{{ ( index .Values.labels "package.checksum" ) }}  {{.Values.name}}-{{.Values.category}}-${PACKAGE_VERSION}.el7.noarch.rpm" | sha256sum -c && \
    rpm -ivh --nodeps *.rpm && \
    cd / && \
    rm -rf /tmp/rpm
{{end}}
{{end}}
excludes:
- ^/tmp
- ^/var/lib/selinux/targeted/tmp
