requires:
- name: "base"
  category: "distro"
  version: ">=0"

steps:
- cp fstab /etc/fstab
{{if .Values.is_opensuse}}
# Mount /tmp as tmpfs by default as set by systemd itself
- cp /usr/share/systemd/tmp.mount /etc/systemd/system
{{end}}
- cp *.mount overlay-setup.service /etc/systemd/system/
- systemctl enable overlay-setup.service
