requires:
- name: "golang"
  category: "build"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
prelude:
{{ if .Values.distribution }}
{{if eq .Values.distribution "opensuse" }}
- zypper in -y git binutils-gold
{{else if eq .Values.distribution "fedora" }}
- dnf install -y git
{{else if eq .Values.distribution "ubuntu" }}
- apt-get install -y git
{{end}}
{{end}}
- |
   PACKAGE_VERSION=v${PACKAGE_VERSION%\-*} && \
   git clone --depth=1 --branch ${PACKAGE_VERSION} https://github.com/derailed/k9s
steps:
- |
   cd k9s && \
   make build && \
   cp execs/k9s /usr/bin
includes:
- /usr/bin/k9s