version: 2
updates:
  - package-ecosystem: "gomod"
    vendor: true
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    labels:
      - dependencies
