packages:
  - &helm
    name: "helm"
    fips: false
    category: "utils"
    version: "3.7.2"
    description: "The Kubernetes Package Manager"
    license: "Apache-2.0 License"
    labels:
      github.repo: "helm"
      github.owner: "helm"
# TODO: fips doesn't work yet
#- !!merge <<: *helm
#  category: "utils-fips"
#  fips: true
