---

arches:
  x86_64:
    local_runner: false
    push_cache: false
    skip_build: false
    skip_docker_build: false

    pipeline: "nightly"
    publishing_pipeline: false
    publish_cloud: false
    publish_toolchain: false
    repository: "releases"
    cache_repository: "build"
    organization: "quay.io/costoolkit"
    skip_tests: false
    flavors: ["green", "blue", "orange"]
    skip_tests_flavor: ["blue","orange"]
    skip_images_flavor: ["blue","orange"]
    release_flavor: ["green"]
    arch: "x86_64"

    on:
      schedule:
        - cron:  '0 20 * * *'
