---

local_runner: false
pipeline: "Pull requests"
push_cache: false
publishing_pipeline: false
publish_cloud: false
skip_build: false
repository: "releases" # releases for prod
cache_repository: "build"
organization: "quay.io/costoolkit"
skip_tests: false
flavors: ["green", "blue", "orange"]
skip_tests_flavor: ["blue","orange"]
skip_images_flavor: ["blue","orange"]
release_flavor: ["green"]

on: 
  pull_request:
    paths:
      - 'conf/**'
      - 'packages/**'
      - 'make/**'
      - '.github/**'
      - 'Makefile'
      - 'tests/**'