---

flavors:
  teal:
    arches:
      x86_64:
        &x86_64
        local_runner: true
        runs_on: [ "self-hosted", "x64" ]
        pipeline: "PR"
        push_cache: false
        publishing_pipeline: false
        publish_toolchain: false
        publish_cloud: false
        skip_build: false
        skip_docker_build: true
        repository: "releases" # releases for prod
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: false
        flavor: "teal"
        skip_tests_flavor: [ "blue", "orange", "green" ]
        skip_images_flavor: [ "blue", "orange", "green" ]
        build_image_qemu: true
        luet_override: ""
        luet_script_override: ""
        run_tests:
          squashfs:
            - "test-recovery"
          nonsquashfs:
            - "test-features"
            - "test-hooks"
            - "test-smoke"
            - "test-fallback"
            - "test-recovery"
            - "test-upgrades-images-signed"
            - "test-upgrades-images-unsigned"
            - "test-upgrades-local"
            - "test-deploys-images-recovery"
        build_image_vbox: true
        build_raw_image: true
        run_raw_image_test: true
        run_installer_test: true
        release_flavor: [ "teal" ]
        arch: "x86_64"
        on:
          pull_request:
            paths:
              - 'conf/**'
              - 'packages/**'
              - 'tests/**'
              - 'make/**'
              - '.github/**'
              - 'Makefile'
              - 'tests/**'
      arm64:
        &arm64
        local_runner: true
        runs_on: [ "self-hosted", "arm64" ]
        pipeline: "PR"
        push_cache: false
        publishing_pipeline: false
        publish_cloud: false
        publish_toolchain: false
        skip_build: false
        luet_script_override: ""
        skip_docker_build: true
        repository: "releases" # releases for prod
        cache_repository: "build"
        organization: "quay.io/costoolkit"
        skip_tests: false
        run_tests:
          squashfs:
            - "test-recovery"
          nonsquashfs:
            - "test-smoke"
            - "test-upgrades-images-unsigned"
        flavor: "teal"
        skip_tests_flavor: [ "blue", "orange", "green"]
        skip_images_flavor: [ "blue", "orange", "green" ]
        skip_images_packer: true
        build_image_qemu: true
        luet_override: ""
        build_image_vbox: false
        build_raw_image: true
        run_raw_image_test: false
        release_flavor: [ "teal" ]
        arch: "arm64"
        # labels required for this job to run, list of labels. All will be required.
        labels: [ "arm64" ]

        on:
          pull_request:
            types: [ "labeled", "synchronize" ]  # synchronize means when the PR is updated
  orange:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "orange"
        build_image_qemu: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
      arm64:
        <<: *arm64
        flavor: "orange"
        build_image_qemu: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
  blue:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "blue"
        build_image_qemu: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
      arm64:
        <<: *arm64
        flavor: "blue"
        build_image_qemu: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
  green:
    arches:
      x86_64:
        <<: *x86_64
        flavor: "green"
        build_image_qemu: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false
      arm64:
        <<: *arm64
        flavor: "green"
        build_image_qemu: false
        build_image_vbox: false
        build_raw_image: false
        run_raw_image_test: false