---


local_runner: false
push_cache: true
skip_build: false

pipeline: "releases"
publishing_pipeline: true
publish_cloud: true

repository: "releases"
cache_repository: "build"
organization: "quay.io/costoolkit"
skip_tests: false
flavors: ["green", "blue", "orange"]
skip_tests_flavor: ["blue","orange"]
skip_images_flavor: ["blue","orange"]
release_flavor: ["green"]

on: 
  push: 
    tags:
      - "v*"