# Default cOS OEM configuration file
#
# This file is part of cOS and will get reset during upgrades.
#
# Before you change this file manually,
# consider copying this file to /usr/local/cloud-config or
# copy the file with a prefix starting by 90, e.g. /oem/91_custom.yaml
name: "Upgrades settings"
stages:
   initramfs:
     - name: "Setup Luet config file"
       files:
       - path: /etc/luet/luet.yaml
         permissions: 0600
         owner: 0
         group: 0
         content: |
                  # For a full reference, see:
                  # https://luet-lab.github.io/docs/docs/getting-started/#configuration
                  logging:
                    color: false
                    enable_emoji: false
                  general:
                     debug: false
                     spinner_charset: 9
                  repositories:
                  - name: "cos"
                    description: "cOS official"
                    type: "docker"
                    enable: true
                    cached: true
                    priority: 1
                    verify: false
                    urls:
                    - "quay.io/costoolkit/releases-:FLAVOR::ARCH:"
     - name: "Setup upgrade channel"
       files:
       - path: /etc/elemental/config.d/upgrade_channel.yaml
         permissions: 0644
         owner: 0
         group: 0
         content: |
                  upgrade:
                    system: 
                      uri: channel:system/cos
                    recovery-system:
                      uri: channel:recovery/cos
