# Default cOS OEM configuration file
# Default cOS OEM configuration file
#
# This file is part of cOS and will get reset during upgrades.
#
# Before you change this file manually,
# consider copying this file to /usr/local/cloud-config or
# copy the file with a prefix starting by 90, e.g. /oem/91_custom.yaml
name: "Branding"
stages:
   initramfs:
     - name: "Branding"
       hostname: "cos"
       files:
        - path: /etc/issue
          content: |
            .-----.
            | .-. |
            | |.| |
            | `-' |
            `-----'

            Welcome to \S !
            IP address \4
            Login with user: root, password: cos
            Start the installer with "elemental install <device>" to install it in the local system
          permissions: 0644
          owner: 0
          group: 0

