image: "{{.Values.image}}"

env:
{{ if .Values.distribution }}
{{if eq .Values.distribution "ubuntu" }}
- DEBIAN_FRONTEND=noninteractive
{{end}}
{{end}}
steps:
{{ if .Values.distribution }}
{{if eq .Values.distribution "opensuse" }}
- zypper in -y --no-recommends {{.Values.packages}} {{.Values.kernel_package}}
- zypper cc
{{else if eq .Values.distribution "fedora" }}
- echo "install_weak_deps=False" >> /etc/dnf/dnf.conf
- dnf install -y {{.Values.packages}} {{.Values.kernel_package}}
- dnf clean all
- |
    kernel=$(ls /boot/vmlinuz-* | head -n1) && \
    ln -sf "${kernel#/boot/}" /boot/vmlinuz
{{else if eq .Values.distribution "ubuntu" }}
# Note for future issues with grub: https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1879558 https://github.com/rancher-sandbox/cOS-toolkit/pull/101#discussion_r621929109
- apt-get update && apt-get install -y {{.Values.packages}} {{.Values.kernel_package}}
- apt-get clean
- |
    kernel=$(ls /boot/vmlinuz-* | head -n1) && \
    ln -sf "${kernel#/boot/}" /boot/vmlinuz
- ln -s /usr/sbin/grub-install /usr/sbin/grub2-install
{{end}}
{{end}}
- kernel=$(ls /lib/modules | head -n1) && depmod -a "${kernel}"
- | 
    echo "uninitialized" > /etc/machine-id && \
    rm /var/lib/dbus/machine-id && \
    ln -sf /etc/machine-id /var/lib/dbus/machine-id
