image: "{{.Values.image}}"

env:
{{ if .Values.distribution }}
{{if eq .Values.distribution "ubuntu" }}
- DEBIAN_FRONTEND=noninteractive
{{end}}
{{end}}
steps:
{{ if .Values.distribution }}
{{if eq .Values.distribution "opensuse" }}
- zypper in -y --no-recommends {{.Values.packages}}
- zypper cc
{{else if eq .Values.distribution "fedora" }}
- echo "install_weak_deps=False" >> /etc/dnf/dnf.conf
- dnf install -y {{.Values.packages}}
- dnf clean all
{{else if eq .Values.distribution "ubuntu" }}
# Note for future issues with grub: https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1879558 https://github.com/rancher-sandbox/cOS-toolkit/pull/101#discussion_r621929109
- apt-get update && apt-get install -y {{.Values.packages}}
- apt-get clean
- ln -s /usr/sbin/grub-install /usr/sbin/grub2-install
{{end}}
{{end}}
- | 
    echo "uninitialized" > /etc/machine-id && \
    rm -f /var/lib/dbus/machine-id && \
    mkdir -p /var/lib/dbus && \
    ln -sf /etc/machine-id /var/lib/dbus/machine-id

# See https://luet-lab.github.io/docs/docs/concepts/packages/specfile/#package-by-container-content
unpack: true
