requires:
- name: "base"
  category: "distro"
  version: ">=0"

steps:
- mkdir /usr/lib/cos
- cp -rfv installer.sh /usr/sbin/cos-installer && chmod +x /usr/sbin/cos-installer
- cp -rfv upgrade.sh /usr/sbin/cos-upgrade && chmod +x /usr/sbin/cos-upgrade
- cp -rfv reset.sh /usr/sbin/cos-reset && chmod +x /usr/sbin/cos-reset
- cp -rfv cos.sh /usr/sbin/cos && chmod +x /usr/sbin/cos
- cp -rfv deploy.sh /usr/sbin/cos-deploy && chmod +x /usr/sbin/cos-deploy
- cp -rfv suc-upgrade.sh /usr/sbin/suc-upgrade && chmod +x /usr/sbin/suc-upgrade
- cp -rfv rebrand.sh /usr/sbin/cos-rebrand && chmod +x /usr/sbin/cos-rebrand
{{ if .Values.codename }}
- sed -i 's/:FLAVOR:/{{.Values.codename}}/g' /usr/sbin/cos
{{end}}
