requires:
- name: "base"
  category: "distro"
  version: ">=0"
steps:
{{if eq .Values.name "cos-config-tmpl"}}
- cp cos-tmpl-render.sh /usr/bin/cos-tmpl-render
{{else}}
- mkdir -p /etc/cos
- cp cos-config /etc/cos/config
{{end}}
