requires:
- name: "base"
  category: "distro"
  version: ">=0"

steps:
{{ if .Values.distribution }}
{{if eq .Values.distribution "opensuse" }}
# Mount /tmp as tmpfs by default as set by systemd itself
- cp /usr/share/systemd/tmp.mount /etc/systemd/system
{{end}}
{{end}}
- cp -r 30cos-immutable-rootfs /usr/lib/dracut/modules.d
- cp 02-cos-immutable-rootfs.conf /etc/dracut.conf.d
