requires:
- name: "base"
  category: "distro"
  version: ">=0"

steps:
{{ if .Values.distribution }}
{{if eq .Values.distribution "opensuse" }}
# Mount /tmp as tmpfs by default as set by systemd itself
- | 
    /bin/bash -c " \
    if [ -e /usr/share/systemd/tmp.mount ]; then \
      cp /usr/share/systemd/tmp.mount /etc/systemd/system; \
    else \
      cp /usr/lib/systemd/system/tmp.mount /etc/systemd/system; \
    fi "
{{end}}
{{end}}
- cp -r 30cos-immutable-rootfs /usr/lib/dracut/modules.d
- cp 02-cos-immutable-rootfs.conf /etc/dracut.conf.d
