requires:
- name: "base-dracut-modules"
  category: "system"
  version: ">=0"
- name: "kernel"
  category: "system"
  version: ">=0"
- name: "immutable-rootfs"
  category: "system"
  version: ">0.3-1"
- name: "cos-setup"
  category: "system"
  version: ">0.6.1"

copy:
# elemental is required in module-setup and embedded in the initramfs. 
# We don't put it in requires to avoid pulling golang sublayers
- package: 
    category: "toolchain"
    name: "elemental-cli"
    version: ">=0"
  source: "/usr/bin/elemental"
  destination: "/usr/bin/elemental"

prelude:
# remove if any
- rm -rf /boot/initrd || true

steps:
# Create initrd
- |
    kernel=$(ls /lib/modules | head -n1) && \
    dracut -f "/boot/initrd-${kernel}" "${kernel}" && \
    ln -sf "initrd-${kernel}" /boot/initrd
