requires:
- name: "base-dracut-modules"
  category: "system"
  version: ">=0"
- name: "kernel"
  category: "system"
  version: ">=0"
- name: "immutable-rootfs"
  category: "system"
  version: ">=0"
- name: "cos-setup"
  category: "system"
  version: ">=0"

copy:
# yip is required in module-setup and embedded in the initramfs. 
# We don't put it in requires to avoid pulling golang sublayers
- package: 
    category: "toolchain"
    name: "yip"
    version: ">=0.9.24"
  source: "/usr/bin/yip"
  destination: "/usr/bin/yip"

steps:
# Create initrd
- |
    kernel=$(ls /lib/modules | head -n1) && \
    dracut -f "/boot/initrd-${kernel}" "${kernel}" && \
    ln -sf "initrd-${kernel}" /boot/initrd
