requires:
- name: "luet"
  category: "system"
  version: ">=0"
- name: "cos-setup"
  category: "system"
  version: ">=0"
- name: "installer"
  category: "utils"
  version: ">=0"
- category: "system"
  name: "yip"
  version: ">=0"
- name: "cloud-config"
  category: "system"
  version: ">=0"
- name: "immutable-rootfs"
  category: "system"
  version: ">=0"

steps:
- sed -i 's/:VERSION:/{{.Values.version}}/g' setup.yaml
- sed -i 's/:PRETTY_NAME:/{{.Values.brand_name}} v{{.Values.version}}/g' setup.yaml
- yip setup.yaml

unpack: true
excludes:
- ^/var/cache/luet
- ^/luetbuild
- ^/srv/.*
- ^/root/.bash_history
- ^/run/reboot-needed

# Zypper
- ^/var/lib/zypp
- ^/var/cache/zypp
- ^/usr/share/zypper
- ^/usr/share/zypp
- ^/usr/share/zsh
- ^/usr/share/licenses/zypper
- ^/usr/bin/zypp-.*
- ^/usr/bin/zypper
- ^/usr/lib/zypp$
- ^/usr/lib/zypper
- ^/usr/lib/rpm
- ^/usr/bin/yzpper
- ^/usr/sbin/zypp-.*
- ^/usr/bin/zypp-.*
- ^/usr/bin/susetags2solv
- ^/run/zypp.*
- ^/etc/zypp
- ^/usr/bin/rpm.*
- ^/var/lib/rpm

# Build deps that got thrown-in by zypper
# XXX: To keep until https://github.com/mudler/luet/issues/173 is delivered,
# or we either create another luet repository for runtime deps
- ^/usr/share/bison
- ^/usr/share/automake
- ^/usr/share/autoconf
- ^/usr/share/aclocal
- ^/usr/share/texinfo
- ^/usr/share/libtool

- texinfo.mo
- git.mo
- flex.mo
- ^/usr/libexec/git
- ^/usr/lib64/pkgconfig
- ^/usr/lib64/ldscripts
- ^/usr/lib64/gcc
- ^/usr/bin/git.*
- ^/usr/bin/gcc.*
- ^/usr/bin/flex.*
- ^/usr/bin/autom.*
- ^/usr/bin/autoconf.*
- ^/usr/bin/bison.*
- ^/usr/bin/libtool.*
- ^/usr/x86_64-suse-linux
- ^/usr/lib64/rpm-plugins
# Yast
- ^/var/lib/YaST2

# Perl
- ^/usr/bin/perl.*
- ^/usr/lib/perl.*

# Wget - we are only shipping curl
- ^/etc/wgetrc
- ^/usr/share/licenses/wget/COPYING
- ^/usr/bin/wget

# General
- ^/usr/include
#- ^/usr/local
- ^/usr/local/bin
- ^/usr/local/go
- ^/usr/local/include
- ^/usr/local/lib.*
- ^/usr/local/man
- ^/usr/local/sbin
- ^/usr/local/share
- ^/usr/local/src
- ^/usr/local/games

# Some golang package leftovers
- ^/root/.cache
