stages:
  default:
    - name: "Default systemd config"
      systemd:
        enable:
        - multi-user.target
        - getty@tty1
        mask:
        - purge-kernels
      commands:
      - systemctl set-default multi-user.target
    - name: "Setup os-release"
      files:
      - path: /etc/os-release
        permissions: 0644
        owner: 0
        group: 0
      environment_file: /etc/os-release
      environment:
        NAME: ":BRANDING:"
        ID: ":BRANDING:"
        ANSI_COLOR: "0;32"
        BUG_REPORT_URL: "https://github.com/rancher/elemental-toolkit/issues"
        HOME_URL: "https://github.com/rancher/elemental-toolkit"
        DOCUMENTATION_URL: "https://github.com/rancher/elemental-toolkit"
        VERSION: ":VERSION:"
        PRETTY_NAME: ":PRETTY_NAME:"
        GRUB_ENTRY_NAME: "cOS :VERSION:"
