style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/rancher-sandbox/cOS-toolkit
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
     title_maps:
       feat: Features
       fix: Bug Fixes
       perf: Performance Improvements
       refactor: Code Refactoring
       ci: Continous Integration
  header:
    pattern: "(.*)"
    pattern_maps:
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
