requires:
- name: "golang"
  category: "build"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
prelude:
{{ if .Values.upx }}
{{ template "distro_install" (dict "Values" .Values "Packages" "upx")}}
{{ end }}
- |
   PACKAGE_VERSION=v${PACKAGE_VERSION%\-*} && \
   git clone --depth=1 --branch ${PACKAGE_VERSION}  https://github.com/rancher/rancherd
steps:
- |
    cd ./rancherd && \
    ./scripts/build
{{ if .Values.upx }}
- upx rancherd/bin/rancherd
{{ end }}
- cp rancherd/bin/rancherd /usr/bin/ && chmod +x /usr/bin/rancherd
includes:
- /usr/bin/rancherd