requires:
- name: "base"
  category: "distro"
  version: ">=0"

steps:
{{if eq .Values.name "grub2-config"}}
- mkdir /etc/cos
- cp config/grub.cfg config/bootargs.cfg /etc/cos
  {{if .Values.distribution}}
    {{if eq .Values.distribution "ubuntu"}}
- grub-editenv /etc/cos/grubenv_firstboot set next_entry=recovery
    {{else}}
- grub2-editenv /etc/cos/grubenv_firstboot set next_entry=recovery
    {{end}}
  {{end}}
{{end}}

{{if eq .Values.name "grub2-efi-image"}}
- mkdir -p /EFI/BOOT
- cp config/grub_efi.cfg /EFI/BOOT/grub.cfg
  {{if .Values.distribution}}
    {{if eq .Values.distribution "opensuse"}}
      {{if .Values.arch }}
        {{if eq .Values.arch "x86_64"}}
- cp /usr/share/grub2/x86_64-efi/grub.efi /EFI/BOOT/bootx64.efi
        {{end}}
       {{if eq .Values.arch "aarch64"}}
- cp /usr/share/grub2/arm64-efi/grub.efi /EFI/BOOT/bootaa64.efi
       {{end}}
     {{end}}
    {{else if eq .Values.distribution "fedora"}}
      {{if eq .Values.arch "x86_64"}}
- grub2-mkimage -O x86_64-efi -o /EFI/BOOT/bootx64.efi -c /EFI/BOOT/grub.cfg -p /grub2 -d /usr/lib/grub/x86_64-efi {{.Values.efi_modules}}
    {{else if eq .Values.arch "aarch64"}}
- mkdir -p /EFI/fedora
- cp -r /boot/efi/EFI/fedora/* /EFI/fedora/
- cp -r /boot/efi/EFI/BOOT/* /EFI/BOOT/
  {{end}}
  {{else if eq .Values.distribution "ubuntu"}}
    {{if eq .Values.arch "x86_64"}}
- grub-mkimage -O x86_64-efi -o /EFI/BOOT/bootx64.efi -c /EFI/BOOT/grub.cfg -p /grub2 -d /usr/lib/grub/x86_64-efi {{.Values.efi_modules}} linuxefi
      {{else if eq .Values.arch "aarch64"}}
- grub-mkimage -O arm64-efi -o /EFI/BOOT/bootaa64.efi -c /EFI/BOOT/grub.cfg -p /grub2 -d /usr/lib/grub/arm64-efi {{.Values.efi_modules_arm64}}
      {{end}}
    {{end}}
  {{end}}
{{end}}

{{if eq .Values.name "grub2-artifacts"}}
- mkdir /grub-artifacts
  {{if .Values.distribution}}
    {{if eq .Values.distribution "opensuse"}}
- cp -rf /usr/share/grub2/* /grub-artifacts
    {{else}}
- cp -rfL /usr/lib/grub/* /grub-artifacts
    {{end}}
  {{end}}

package_dir: /grub-artifacts
{{end}}
