requires:
- name: "base"
  category: "distro"
  version: ">=0"

prelude:
{{if eq .Values.name "grub2"}}
  {{if .Values.distribution}}
    {{if eq .Values.distribution "opensuse"}}
- zypper in -y --no-recommends syslinux
- zypper cc
- grub2-mkimage -O i386-pc -o /usr/share/grub2/i386-pc/core.img -p /boot/grub2 -d /usr/share/grub2/i386-pc {{.Values.base_mod}} {{.Values.bios_mod}}
- cat /usr/share/grub2/i386-pc/cdboot.img /usr/share/grub2/i386-pc/core.img > /usr/share/grub2/i386-pc/eltorito.img
    {{else if eq .Values.distribution "fedora"}}
- dnf install -y syslinux
- dnf clean all
- grub2-mkimage -O i386-pc -o /usr/lib/grub/i386-pc/core.img -p /boot/grub2 -d /usr/lib/grub/i386-pc {{.Values.base_mod}} {{.Values.bios_mod}}
- cat /usr/lib/grub/i386-pc/cdboot.img /usr/lib/grub/i386-pc/core.img > /usr/lib/grub/i386-pc/eltorito.img
    {{else if eq .Values.distribution "ubuntu"}}
- apt-get update && apt-get install -y syslinux
- apt-get clean
- grub-mkimage -O i386-pc -o /usr/lib/grub/i386-pc/core.img -p /boot/grub2 -d /usr/lib/grub/i386-pc {{.Values.base_mod}} {{.Values.bios_mod}}
- cat /usr/lib/grub/i386-pc/cdboot.img /usr/lib/grub/i386-pc/core.img > /usr/lib/grub/i386-pc/eltorito.img
    {{end}}
  {{end}}
{{end}}

steps:
{{if .Values.distribution}}

  {{if eq .Values.distribution "opensuse"}}
    {{if eq .Values.name "grub2"}}
- mkdir -p /boot/x86_64/loader/grub2/fonts && cp -p /usr/share/grub2/unicode.pf2 /boot/x86_64/loader/grub2/fonts
- mkdir -p /boot/grub2/i386-pc && cp -p /usr/share/grub2/i386-pc/* /boot/grub2/i386-pc/
- mkdir -p /boot/grub2/x86_64-efi/ && cp -p /usr/share/grub2/x86_64-efi/* /boot/grub2/x86_64-efi/
- cp -p /usr/share/grub2/i386-pc/eltorito.img /usr/share/grub2/i386-pc/boot_hybrid.img /usr/share/syslinux/isolinux.bin /usr/share/syslinux/menu.c32 /usr/share/syslinux/chain.c32 /usr/share/syslinux/mboot.c32 /boot/x86_64/loader
- cp -p config/grub_live.cfg /boot/grub2/grub.cfg
    {{end}}
    {{if eq .Values.name "grub2-efi-image"}}
- mkdir -p /efi/boot && cp /usr/share/grub2/x86_64-efi/grub.efi /efi/boot/bootx64.efi
- cp config/grub_live_efi.cfg /efi/boot/grub.cfg
    {{end}}

  {{else if eq .Values.distribution "fedora"}}
    {{if eq .Values.name "grub2"}}
- mkdir -p /boot/x86_64/loader/grub2/fonts && cp -p /usr/share/grub/unicode.pf2 /boot/x86_64/loader/grub2/fonts
- mkdir -p /boot/grub2/i386-pc && cp -p /usr/lib/grub/i386-pc/* /boot/grub2/i386-pc/
- mkdir -p /boot/grub2/x86_64-efi/ && cp -p /usr/lib/grub/x86_64-efi/* /boot/grub2/x86_64-efi/
- cp -p /usr/lib/grub/i386-pc/eltorito.img /usr/lib/grub/i386-pc/boot_hybrid.img /usr/share/syslinux/isolinux.bin /usr/share/syslinux/menu.c32 /usr/share/syslinux/chain.c32 /usr/share/syslinux/mboot.c32 /loader
- cp -p config/grub_live.cfg /boot/grub2/grub.cfg
    {{end}}
    {{if eq .Values.name "grub2-efi-image"}}
- mkdir -p /EFI/BOOT/ && cp /boot/efi/EFI/fedora/grubx64.efi /EFI/BOOT/grubx64.efi
- cp config/grub_live_efi.cfg /EFI/BOOT/grub.cfg
    {{end}}

  {{else if eq .Values.distribution "ubuntu"}}
    {{if eq .Values.name "grub2"}}
- mkdir -p /boot/x86_64/loader/grub2/fonts && cp -p /usr/share/grub/unicode.pf2 /boot/x86_64/loader/grub2/fonts
- mkdir -p /boot/grub2/i386-pc && cp -p /usr/lib/grub/i386-pc/* /boot/grub2/i386-pc/
- mkdir -p /boot/grub2/x86_64-efi/ && cp -p /usr/lib/grub/x86_64-efi/* /boot/grub2/x86_64-efi/
- cp -p /usr/lib/grub/i386-pc/eltorito.img /usr/lib/grub/i386-pc/boot_hybrid.img /usr/lib/ISOLINUX/isolinux.bin /usr/lib/syslinux/modules/bios/menu.c32 /usr/lib/syslinux/modules/bios/chain.c32 /usr/lib/syslinux/modules/bios/mboot.c32 /loader
- cp -p config/grub_live.cfg /boot/grub2/grub.cfg
    {{end}}
    {{if eq .Values.name "grub2-efi-image"}}
- mkdir -p /boot/efi/EFI/BOOT
- grub-mkimage -O x86_64-efi -o /boot/efi/EFI/BOOT/bootx64.efi -p /boot/grub -d /usr/lib/grub/x86_64-efi {{.Values.base_mod}} {{.Values.efi_mod}}
- cp config/grub_live_efi.cfg  /boot/efi/EFI/BOOT/grub.cfg
    {{end}}
  {{end}}
{{end}}

{{if eq .Values.name "grub2-config"}}
- mkdir /etc/cos
- cp config/grub.cfg config/bootargs.cfg /etc/cos
{{end}}

{{if eq .Values.name "grub2-artifacts"}}
- mkdir /grub-artifacts
  {{if .Values.distribution}}
    {{if eq .Values.distribution "opensuse"}}
- cp -rf /usr/share/grub2/* /grub-artifacts
    {{else}}
- cp -rf /usr/share/grub/* /grub-artifacts
    {{end}}
  {{end}}

package_dir: /grub-artifacts
{{end}}
