image: "{{.Values.tool_image}}"
unpack: true
steps:
{{ if .Values.tool_image_distribution }}
{{if eq .Values.tool_image_distribution "opensuse" }}
- zypper in -y --no-recommends {{.Values.tools_packages}}
- zypper cc
{{else if eq .Values.tool_image_distribution "fedora" }}
- echo "install_weak_deps=False" >> /etc/dnf/dnf.conf
- dnf install -y {{.Values.tools_packages}}
- dnf clean all
{{else if eq .Values.tool_image_distribution "ubuntu" }}
# Note for future issues with grub: https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1879558 https://github.com/rancher-sandbox/cOS-toolkit/pull/101#discussion_r621929109
- apt-get update && apt-get install -y {{.Values.tools_packages}}
- apt-get clean
- ln -s /usr/sbin/grub-install /usr/sbin/grub2-install
{{end}}
{{end}}