{{ if ne .Values.codename "teal" }}
requires:
- name: "base"
  category: "distro"
  version: ">=0"
{{ else }}
image: {{.Values.tool_image}}
{{ end }}

package_dir: /{{.Values.name}}

prelude:
  {{ if .Values.distribution }}
  {{if eq .Values.distribution "opensuse" }}
- zypper install -y autoconf libtool git gcc make
  {{else if eq .Values.distribution "fedora" }}
- dnf install -y autoconf libtool git gcc make
  {{else if eq .Values.distribution "ubuntu" }}
- apt-get update
- apt-get install -y autoconf libtool git gcc make
  {{end}}
  {{end}}

steps:
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && \
  mkdir -p /luetbuild/{{ ( index .Values.labels "github.repo" ) }} && \
  cd /luetbuild/{{ ( index .Values.labels "github.repo" ) }} && \
  git clone https://github.com/{{ ( index .Values.labels "github.owner" ) }}/{{ ( index .Values.labels "github.repo" ) }} && \
  cd {{ ( index .Values.labels "github.repo" ) }} && git checkout jq-"$PACKAGE_VERSION" -b build && \
  git submodule update --init && autoreconf -fi && ./configure --with-oniguruma=builtin --disable-maintainer-mode && \
  make LDFLAGS=-all-static && \
  mkdir -p /${PACKAGE_NAME}/usr/bin && \
  cp ./${PACKAGE_NAME} /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
  chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
