requires:
- name: "golang"
  category: "build"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
prelude:
- |
   PACKAGE_VERSION=v${PACKAGE_VERSION%\-*} && \
   git clone --depth=1 --branch ${PACKAGE_VERSION} https://github.com/containerd/nerdctl
steps:
- |
   cd nerdctl && \
   make binaries && \
   make BINDIR=/usr/bin install
includes:
- /usr/bin/nerdctl