requires:
- name: "base"
  category: "distro"
  version: ">=0"
steps:
- mkdir -p /usr/lib/systemd/system
- mkdir -p /etc/dracut.conf.d
- cp 02-cos-setup-initramfs.conf /etc/dracut.conf.d
- cp -rfv *.service /usr/lib/systemd/system
- cp -rfv *.timer /usr/lib/systemd/system
- systemctl enable cos-setup-rootfs.service
- systemctl enable cos-setup-initramfs.service
- systemctl enable cos-setup-reconcile.timer
- systemctl enable cos-setup-fs.service
- systemctl enable cos-setup-boot.service
- systemctl enable cos-setup-network.service
