stages:
   network:
     - name: "Setup k3s"
       directories:
       - path: "/usr/local/bin"
         permissions: 0755
         owner: 0
         group: 0
       commands:
       - |
            curl -sfL https://get.k3s.io | \
            INSTALL_K3S_VERSION="v1.20.4+k3s1" \
            INSTALL_K3S_EXEC="--data-dir /usr/local/rancher/k3s" \
            sh -
     - name: "Setup Longhorn"
       commands:
       - |
          curl https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/deploy/longhorn.yaml | \
          sed -e 's/#- name: KUBELET_ROOT_DIR/- name: KUBELET_ROOT_DIR/g' -e 's$#  value: /var/lib/rancher/k3s/agent/kubelet$  value: /var/lib/kubelet$g'  | \
          sed -e 's|default-data-path:|default-data-path: /usr/local/rancher/longhorn|g' | \
          k3s --data-dir /usr/local/rancher/k3s kubectl apply -f -
     - name: "Setup helm"
       commands:
       - |
          if [ ! -e "/usr/local/bin/helm" ]; then
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          fi
     - name: "Setup epinio"
       commands:
       - |
          export IMG_SHA256="e7525bbb417c35702c4ffef52c7c77b67e32c44d581f6916ae351558f494d6d8"
          curl -fSL "https://github.com/epinio/epinio/releases/download/v0.0.22/epinio-linux-amd64" -o "/usr/local/bin/epinio" \
          && echo "${IMG_SHA256}  /usr/local/bin/epinio" | sha256sum -c - \
          && chmod a+x "/usr/local/bin/epinio"

          KUBECONFIG=/etc/rancher/k3s/k3s.yaml EPINIO_CONFIG=/usr/local/epinio.yaml epinio install
name: "Opinionated platform that runs on Kubernetes, that takes you from App to URL in one step."
