requires:
  - name: "golang"
    category: "build"
    version: ">=0"
env:
  - PATH=$PATH:/usr/local/go/bin
  - GOPATH=/luetbuild/go
  - GO111MODULE=on
  - CGO_ENABLED=0
  - LDFLAGS="-s -w"
prelude:
  {{ if .Values.distribution }}
  {{if eq .Values.distribution "opensuse" }}
- zypper in -y git
  {{else if eq .Values.distribution "fedora" }}
- dnf install -y git
  {{else if eq .Values.distribution "ubuntu" }}
- apt-get install -y git
  {{end}}
  {{end}}
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  mkdir -p /luetbuild/go/src/github.com/mikefarah && cd /luetbuild/go/src/github.com/mikefarah && \
  git clone https://github.com/mikefarah/yq && cd yq && git checkout "v${PACKAGE_VERSION}" -b build
steps:
  - |
    PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
    cd /luetbuild/go/src/github.com/mikefarah/yq && go build --ldflags "$LDFLAGS" && mv yq /usr/bin/yq
includes:
  - /usr/bin/yq