requires:
- name: "cos-setup"
  category: "system"
  version: ">=0"
- name: "cos-config-tmpl" 
  category: "utils"
  version: ">=0"
- name: "cos-config" 
  category: "system"
  version: ">=0"

steps:
- mkdir -p /system /oem
- cp -rfv oem /system
- chmod -R 600 /system/oem
- cos-tmpl-render /system/oem/00_rootfs.yaml.tmpl
- cos-tmpl-render /system/oem/06_recovery.yaml.tmpl
{{ if .Values.codename }}
- sed -i 's/:FLAVOR:/{{.Values.codename}}/g' /system/oem/02_upgrades.yaml
{{end}}
{{ if .Values.arch }}
  {{if eq .Values.arch "x86_64"}}
- sed -i 's/:ARCH://g' /system/oem/02_upgrades.yaml
  {{end}}
  {{if eq .Values.arch "aarch64"}}
- sed -i 's/:ARCH:/-arm64/g' /system/oem/02_upgrades.yaml
  {{end}}
{{end}}
