name: autorelease
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 6'
concurrency:
  group: ci-autorelease-${{ github.repository }}
  cancel-in-progress: true
jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: mikefarah/yq@v4.25.1
      - name: Get current tag
        id: current
        run: |
          CURRENT_TAG=$(yq '.packages[]|select(.name=="cos" and .category =="system")|.version' packages/cos/collection.yaml)
          echo "Current Tag: v$CURRENT_TAG"
          echo "::set-output name=tag::v$CURRENT_TAG"
      - name: Get previous tag
        id: previous
        run: |
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags)
          echo "Previous Tag: $PREVIOUS_TAG"
          echo "::set-output name=tag::$PREVIOUS_TAG"
      - name: Check if same tag as previous
        id: check
        run: |
          if [[ "${{steps.current.outputs.tag}}" == "${{steps.previous.outputs.tag}}" ]]; then
            echo "Tag doesnt need bump"
            echo "::set-output name=bumped::false"
          else
            echo "Tag needs bump"
            echo "::set-output name=bumped::true"
          fi
      - uses: rickstaa/action-create-tag@v1
        if: steps.check.outputs.bumped == 'true'
        with:
          tag: ${{steps.current.outputs.tag}}
          message: "Bump tag"