name: Build cOS Pull requests-green-arm64
on: 
 pull_request:
   types:
     - labeled
     - synchronize
concurrency:
  group: ci-Pull requests-green-arm64-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  tests-squashfs-green:
    env:
      VAGRANT_CPU: 3
      VAGRANT_MEMORY: 10240
      ARCH: arm64
      LUET_ARCH: arm64
      VAGRANT_FIRMWARE: /usr/share/qemu-efi-aarch64/QEMU_EFI.fd
    runs-on: [ "self-hosted", "arm64" ]
    strategy:
      matrix:
        test: ["test-features",]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/checkout@v2
      - name: Deps
        run: |
          sudo -E make deps
      - name: Download vagrant box
        run: |
          curl -L https://github.com/Itxaka/cOS-toolkit/releases/download/v0.7.0-testing/cOS_green_arm64.box -o packer/cos_arm64.box
      - name: Run tests 🔧
        shell: sh
        run: |
          export PATH=$PATH:/usr/local/go/bin
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          make test-clean
          make prepare-test
          make ${{ matrix.test }}
      - name: Cleanup
        if: always()
        run: |
          make test-clean
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cOS-squashfs-${{ matrix.test }}.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cOS-squashfs-${{ matrix.test }}.serial.zip
          path: tests/serial_port1
          if-no-files-found: warn