name: Build cOS self-hosted
on:
 pull_request:
   branches: [ master ]
   types: [ labeled ]

jobs:
  build:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    strategy:
      matrix:
       include:
         - flavor: "opensuse"

    env:
      FLAVOR: ${{ matrix.flavor }}
    steps:
    - name: Cleanup
      run: |
        sudo rm -rf /home/cos/actions-runner/_work/cOS-toolkit/cOS-toolkit/build

    - uses: actions/checkout@v2

    - run: |
        git fetch --prune --unshallow

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y jq make

    - name: Login to DockerHub Registry
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Set Push options
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo "BUILD_ARGS=--push --only-target-package --pull" >> $GITHUB_ENV

    - name: Install deps
      run: |
        sudo -E make deps

    - name: Validate 🌳
      run: |
        make validate

    - name: Build packages 🔧
      run: |
        sudo -E make build
        ls -liah $PWD/build

    - name: Create repo
      run: |
        sudo -E make create-repo
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.flavor }}
        path: build

  iso:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    needs: build
    strategy:
      matrix:
       include:
         - flavor: "opensuse"
#         - flavor: "fedora"
    steps:
    - name: Cleanup
      run: |
        sudo rm -rf /home/cos/actions-runner/_work/cOS-toolkit/cOS-toolkit/build
    - uses: actions/checkout@v2
    - name: Download result for build
      uses: actions/download-artifact@v2
      with:
        name: build-${{ matrix.flavor }}
        path: build
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y xorriso squashfs-tools dosfstools
        sudo -E make deps

    - name: Build ISO from local build 🔧
      if: github.event_name != 'schedule' && !startsWith(github.ref, 'refs/tags/')
      run: |
        sudo -E make local-iso
        COS_VERSION=$(yq r packages/cos/definition.yaml 'version')
        mv *.iso cOS-$COS_VERSION.iso
        mv *.sha256 cOS-$COS_VERSION.iso.sha256

    - name: Build ISO from remote repositories 🔧
      if: github.event_name == 'schedule' || startsWith(github.ref, 'refs/tags/')
      run: |
        sudo -E make iso
        COS_VERSION=$(yq r packages/cos/definition.yaml 'version')
        mv *.iso cOS-$COS_VERSION.iso
        mv *.sha256 cOS-$COS_VERSION.iso.sha256

    - uses: actions/upload-artifact@v2
      with:
        name: cOS-${{ matrix.flavor }}.iso.zip
        path: |
          *.iso
          *.sha256
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: luet-build-${{ matrix.flavor }}.log
        path: isowork/*.log

  qemu:
      runs-on: self-hosted
      if: contains(github.event.pull_request.labels.*.name, 'safe to test')
      needs: iso

      strategy:
        matrix:
          include:
            - flavor: "opensuse"
#            - flavor: "fedora"
      steps:
      - name: Cleanup
        run: |
          sudo rm -rf /home/cos/actions-runner/_work/cOS-toolkit/cOS-toolkit/build
      - uses: actions/checkout@v2
      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-system qemu-kvm
          sudo -E make deps
          sudo luet install -y utils/packer

      - name: Build QEMU Image 🔧
        run: |
          PACKER_ARGS="-var='accellerator=none' -var='sleep=5m' -only qemu" make packer
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.qcow
          path: |
            packer/*.tar.gz

  qemu-vagrant:
      runs-on: self-hosted
      if: contains(github.event.pull_request.labels.*.name, 'safe to test')
      needs: iso

      strategy:
        matrix:
          include:
            - flavor: "opensuse"
#            - flavor: "fedora"
      steps:
      - name: Cleanup
        run: |
          sudo rm -rf /home/cos/actions-runner/_work/cOS-toolkit/cOS-toolkit/build
      - uses: actions/checkout@v2
      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-system qemu-kvm
          sudo -E make deps
          sudo luet install -y utils/packer

      - name: Build QEMU Image 🔧
        run: |
          PACKER_ARGS="-var='accellerator=none' -var='sleep=5m' -var='feature=vagrant' -only qemu" make packer
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}-QEMU.box
          path: |
            packer/*.box

  vbox:
      runs-on: macos-10.15
      needs: iso
      strategy:
        matrix:
          include:
            - flavor: "opensuse"
#            - flavor: "fedora"
      steps:
      - name: Cleanup
        run: |
          sudo rm -rf /home/cos/actions-runner/_work/cOS-toolkit/cOS-toolkit/build
      - uses: actions/checkout@v2
      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip

      # - name: Install deps
      #   run: |
      #     brew tap hashicorp/tap
      #     brew install hashicorp/tap/packer
      - name: Build VBox Image 🔧
        run: |
          PACKER_ARGS="-var='sleep=5m' -only virtualbox-iso" make packer
          ls packer
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.ova
          path: |
            packer/*.tar.gz

  vbox-vagrant:
      runs-on: macos-10.15
      needs: iso
      strategy:
        matrix:
          include:
            - flavor: "opensuse"
#            - flavor: "fedora"
      steps:
      - name: Cleanup
        run: |
          sudo rm -rf /home/cos/actions-runner/_work/cOS-toolkit/cOS-toolkit/build
      - uses: actions/checkout@v2
      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip

      # - name: Install deps
      #   run: |
      #     brew tap hashicorp/tap
      #     brew install hashicorp/tap/packer
      - name: Build VBox Image 🔧
        run: |
          PACKER_ARGS="-var='sleep=5m' -var='feature=vagrant' -only virtualbox-iso" make packer
          ls packer

      - uses: actions/upload-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}-vbox.box
          path: |
            packer/*.box

  tests:
      runs-on: macos-10.15
      needs: vbox-vagrant
      strategy:
        matrix:
          include:
            - flavor: "opensuse"
#            - flavor: "fedora"
      steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: Download vagrant box
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}-vbox.box
          path: packer

      - name: Run tests 🔧
        run: |
          export GOPATH="/Users/runner/go"
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          PATH=$PATH:$GOPATH/bin
          make test

  publish:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    needs: tests
    strategy:
      matrix:
       include:
         - flavor: "opensuse"
         - flavor: "fedora"
    env:
      FLAVOR: ${{ matrix.flavor }}
    steps:
    - name: Cleanup
      run: |
        sudo rm -rf /home/cos/actions-runner/_work/cOS-toolkit/cOS-toolkit/build
    - uses: actions/checkout@v2
    - name: Download result for build
      uses: actions/download-artifact@v2
      with:
        name: build-${{ matrix.flavor }}
        path: build
    - run: |
        git fetch --prune --unshallow

    - name: Login to DockerHub Registry
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Set Push options
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo "BUILD_ARGS=--push --only-target-package --pull" >> $GITHUB_ENV

    - name: Install deps
      run: |
        sudo -E make deps

    - name: Publish to DockerHub 🚀
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        sudo -E make publish-repo

  github-release:
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: self-hosted
      needs: tests
      strategy:
        matrix:
         include:
           - flavor: "opensuse"
           - flavor: "fedora"
      steps:
      - name: Cleanup
        run: |
          sudo rm -rf /home/cos/actions-runner/_work/cOS-toolkit/cOS-toolkit/build
      - uses: actions/checkout@v2
      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip
          path: release
      - name: Download vagrant box
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}-vbox.box
          path: release
      - name: Download OVA image
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.ova
          path: release
      - name: Download QCOW image
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.qcow
          path: release
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
