name: Build & test

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      flavor:
        required: true
        type: string

concurrency:
  group: ci-${{ inputs.flavor }}-${{ inputs.arch }}-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  # detect step checks what machines the later steps should run on
  detect:
    runs-on: ubuntu-latest
    outputs:
      build-runs-on: ${{ steps.detect.outputs.buildon }}
      tests-runs-on: ${{ steps.detect.outputs.testson }}
      tests: ${{ steps.detect.outputs.tests }}
    steps:
      - id: detect
        env:
          FLAVOR: ${{ inputs.flavor }}
        run: |
          case "${{inputs.arch}}" in
          x86_64)
            echo "buildon='ubuntu-latest'" >> $GITHUB_OUTPUT
            echo "testson='macos-latest'" >> $GITHUB_OUTPUT
            if [ "${FLAVOR}" == green ]; then
              echo "tests=['test-upgrade', 'test-recovery', 'test-fallback', 'test-fsck', 'test-grubfallback']" >> $GITHUB_OUTPUT
            else
              echo "tests=[]" >> $GITHUB_OUTPUT
            fi
            ;;
          aarch64)
            echo "buildon=['self-hosted', 'arm64']" >> $GITHUB_OUTPUT
            echo "testson=['self-hosted', 'arm64']" >> $GITHUB_OUTPUT
            echo "tests=['test-smoke']" >> $GITHUB_OUTPUT ;;
          esac

  build-iso:
    needs: detect
    runs-on: ${{ fromJson(needs.detect.outputs.build-runs-on) }}
    env:
      FLAVOR: ${{ inputs.flavor }}
      ARCH: ${{ inputs.arch }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Cached ISO
        id: cache-iso
        uses: actions/cache/restore@v3
        env:
          cache-name: pr-iso-build-${{ inputs.arch }}-${{ inputs.flavor }}
          enableCrossOsArchive: true
          lookup-only: true
        with:
          path: /tmp/*.iso
          key: ${{ env.cache-name }}-${{ hashFiles('Dockerfile', '**/go.sum', '**/pkg/**', '**/examples/**', '**/cmd/**', '**/vendor/**', '**/Makefile', '**/main.go') }}
      - if: ${{ steps.cache-iso.outputs.cache-hit != 'true' }}
        name: Build toolkit
        run: |
          make build
      - if: ${{ steps.cache-iso.outputs.cache-hit != 'true' }}
        name: Build ISO
        run: |
          make build-iso
          sudo mv build/elemental-${{ env.FLAVOR }}.${{ env.ARCH}}.iso /tmp/
      - if: ${{ steps.cache-iso.outputs.cache-hit != 'true' }}
        name: Save ISO
        id: save-iso
        uses: actions/cache/save@v3
        env:
          cache-name: pr-iso-build-${{ inputs.arch }}-${{ inputs.flavor }}
        with:
          path: /tmp/*.iso
          key: ${{ env.cache-name }}-${{ hashFiles('Dockerfile', '**/go.sum', '**/pkg/**', '**/examples/**', '**/cmd/**', '**/vendor/**', '**/Makefile', '**/main.go') }}
          enableCrossOsArchive: true
  
  build-disk:
    needs: detect
    runs-on: ${{ fromJson(needs.detect.outputs.build-runs-on) }}
    env:
      FLAVOR: ${{ inputs.flavor }}
      ARCH: ${{ inputs.arch }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Checks cached Disk
        uses: actions/cache/restore@v3
        id: cache-check
        env:
          cache-name: pr-disk-build-${{ inputs.arch }}-${{ inputs.flavor }}
        with:
          path: /tmp/*.qcow2
          key: ${{ env.cache-name }}-${{ hashFiles('Dockerfile', '**/go.sum', '**/pkg/**', '**/examples/**', '**/cmd/**', '**/vendor/**', '**/Makefile', '**/main.go') }}
          enableCrossOsArchive: true
          lookup-only: true
      - if: ${{ steps.cache-check.outputs.cache-hit != 'true' }}
        name: Cleanup worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
          sudo df -h
      - if: ${{ steps.cache-check.outputs.cache-hit != 'true' }}
        name: Install to disk
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends qemu-utils coreutils
          make ARCH=${{ env.ARCH }} build-os
          sudo -E make ARCH=${{ env.ARCH }} build-disk
          sudo mv build/elemental-${{ env.FLAVOR }}.${{ env.ARCH}}.qcow2 /tmp/
      - if: ${{ steps.cache-check.outputs.cache-hit != 'true' }}
        name: Save cached disk
        id: cache-disk
        uses: actions/cache/save@v3
        env:
          cache-name: pr-disk-build-${{ inputs.arch }}-${{ inputs.flavor }}
        with:
          path: /tmp/*.qcow2
          key: ${{ env.cache-name }}-${{ hashFiles('Dockerfile', '**/go.sum', '**/pkg/**', '**/examples/**', '**/cmd/**', '**/vendor/**', '**/Makefile', '**/main.go') }}
          enableCrossOsArchive: true

  tests-matrix:
    needs: 
      - build-disk
      - detect
    runs-on: ${{ fromJson(needs.detect.outputs.tests-runs-on) }}
    env:
      FLAVOR: ${{ inputs.flavor }}
      ARCH: ${{ inputs.arch }}
      COS_TIMEOUT: 1600
    strategy:
      matrix:
        test: ${{ fromJson(needs.detect.outputs.tests) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Install deps
        run: |
          make test-deps
      - run: |
          git fetch --prune --unshallow
      - name: Cached Disk
        id: cache-disk
        uses: actions/cache/restore@v3
        env:
          cache-name: pr-disk-build-${{ inputs.arch }}-${{ inputs.flavor }}
        with:
          path: /tmp/*.qcow2
          key: ${{ env.cache-name }}-${{ hashFiles('Dockerfile', '**/go.sum', '**/pkg/**', '**/examples/**', '**/cmd/**', '**/vendor/**', '**/Makefile', '**/main.go') }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true
      - if: ${{ env.ARCH == 'x86_64' }} 
        name: Run VM script dependencies
        run: |
          brew install bash coreutils
      - if: ${{ env.ARCH == 'x86_64' }} 
        name: Prepare test (x86_64)
        run: |
          make DISK=/tmp/elemental-${{ env.FLAVOR }}.${{ env.ARCH}}.qcow2 ELMNTL_ACCEL=hvf ELMNTL_TARGETARCH=${{ env.ARCH }} ELMNTL_FIRMWARE=$(find /usr/local/Cellar/qemu -name edk2-${{ env.ARCH }}-code.fd -print -quit) prepare-test
      - if: ${{ env.ARCH == 'aarch64' }} 
        name: Prepare test (aarch64)
        run: |
          make DISK=/tmp/elemental-${{ env.FLAVOR }}.${{ env.ARCH}}.qcow2 ELMNTL_ACCEL=none ELMNTL_MACHINETYPE=virt ELMNTL_TARGETARCH=${{ env.ARCH }} ELMNTL_FIRMWARE=/usr/share/AAVMF/AAVMF_CODE.fd prepare-test
      - name: Run ${{ matrix.test }}
        run: |
          make DISK=/tmp/elemental-${{ env.FLAVOR }}.${{ env.ARCH}}.qcow2 ${{ matrix.test }}
      # TODO include other logs SUT collects on failure
      - name: Upload serial console for ${{ matrix.test }}
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: serial-${{ env.ARCH }}-${{ env.FLAVOR }}-${{ matrix.test }}.log
          path: tests/serial.log
          if-no-files-found: error
      - name: Upload qemu stdout for ${{ matrix.test }}
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: vmstdout-${{ env.ARCH }}-${{ env.FLAVOR }}-${{ matrix.test }}.log
          path: tests/vmstdout
          if-no-files-found: error
      - name: Stop test VM
        if: always()
        run: |
          make test-clean

  test-installer:
    needs: 
      - build-iso
      - detect
    runs-on: ${{ fromJson(needs.detect.outputs.tests-runs-on) }}
    env:
      FLAVOR: ${{ inputs.flavor }}
      ARCH: ${{ inputs.arch }}
      COS_TIMEOUT: 1600
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Install deps
        run: |
          make test-deps
      - run: |
          git fetch --prune --unshallow
      - name: Cached ISO
        id: cache-iso
        uses: actions/cache/restore@v3
        env:
          cache-name: pr-iso-build-${{ inputs.arch }}-${{ inputs.flavor }}
        with:
          path: /tmp/*.iso
          key: ${{ env.cache-name }}-${{ hashFiles('Dockerfile', '**/go.sum', '**/pkg/**', '**/examples/**', '**/cmd/**', '**/vendor/**', '**/Makefile', '**/main.go') }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true
      - if: ${{ env.ARCH == 'x86_64' }} 
        name: Run VM script dependencies
        run: |
          brew install bash coreutils
      - if: ${{ env.ARCH == 'x86_64' }} 
        name: Prepare test (x86_64)
        run: |
          make ISO=/tmp/elemental-${{ env.FLAVOR }}.${{ env.ARCH}}.iso ELMNTL_ACCEL=hvf ELMNTL_TARGETARCH=${{ env.ARCH }} ELMNTL_FIRMWARE=$(find /usr/local/Cellar/qemu -name edk2-${{ env.ARCH }}-code.fd -print -quit) prepare-installer-test
      - if: ${{ env.ARCH == 'aarch64' }} 
        name: Prepare test (aarch64)
        run: |
          make ISO=/tmp/elemental-${{ env.FLAVOR }}.${{ env.ARCH}}.iso ELMNTL_ACCEL=none ELMNTL_MACHINETYPE=virt ELMNTL_TARGETARCH=${{ env.ARCH }} ELMNTL_FIRMWARE=/usr/share/AAVMF/AAVMF_CODE.fd prepare-installer-test
      - name: Run installer test
        run: |
          make ISO=/tmp/elemental-${{ env.FLAVOR }}.${{ env.ARCH}}.iso test-installer
      # TODO include other logs SUT collects on failure
      - name: Upload serial console for installer tests
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: serial-${{ env.ARCH }}-${{ env.FLAVOR }}-installer.log
          path: tests/serial.log
          if-no-files-found: error
      - name: Upload qemu stdout for installer tests
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: vmstdout-${{ env.ARCH }}-${{ env.FLAVOR }}-installer.log
          path: tests/vmstdout
          if-no-files-found: error
      - name: Stop test VM
        if: always()
        run: |
          make test-clean
