name: Build Site
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Install deps
        run: |
          npm install postcss-cli
          npm install autoprefixer
          sudo bash ./scripts/get_luet.sh
          sudo luet install -y toolchain/yq
      - name: Build pages
        run: |
           make docs-build
           mv docs/public ./
           ls -liah public/