name: Publish Site
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
   - cron: 0 20 * * *
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install deps
        run: |
          npm install postcss-cli
          npm install autoprefixer
          apt install -y --no-install-recommends hugo
      - name: Build package docs
        run: |
           make build-docs
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public

