name: nightly

on:
  workflow_dispatch:
  #schedule:
    # run at 02:30 UTC every night
    #- cron:  '30 2 * * *'

jobs:
  build-matrix:
    strategy:
      matrix:
        flavor: ['green', 'tumbleweed']
    uses: ./.github/workflows/build_and_test_arm.yaml
    with:
      flavor: ${{ matrix.flavor }}
