name: PR
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - tests/**
      - make/**
      - Makefile
      - .github/**
      - pkg/**
      - cmd/**
      - go.{mod,sum}
      - examples/**

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      arch: ${{ steps.set-matrix.outputs.arch }}
    steps:
    - id: set-matrix
      run: |
        if [ "${{ contains(github.event.pull_request.labels.*.name, 'arm64') }}" == "true" ]; then
          echo "arch=['x86_64', 'aarch64']" >> $GITHUB_OUTPUT
        else
          echo "arch=['x86_64']" >> $GITHUB_OUTPUT
        fi
        
  build-matrix:
    needs: detect
    strategy:
      matrix:
        arch: ${{fromJson(needs.detect.outputs.arch)}}
        flavor: ['green', 'tumbleweed', 'blue']
    uses: ./.github/workflows/build_and_test.yaml
    with:
      arch: ${{ matrix.arch }}
      flavor: ${{ matrix.flavor }}
