name: PR
on:
  pull_request:
    paths:
      - tests/**
      - make/**
      - Makefile
      - .github/**
      - pkg/**
      - cmd/**
      - go.mod
      - go.sum
      - examples/**

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      flavor: ${{ steps.set-matrix.outputs.flavor }}
    steps:
    - id: set-matrix
      run: |
        if [ "${{ contains(github.event.pull_request.labels.*.name, 'all-distros') }}" == "true" ]; then
          echo "flavor=['green', 'tumbleweed', 'blue', 'orange']" >> $GITHUB_OUTPUT
        else
          echo "flavor=['green']" >> $GITHUB_OUTPUT
        fi

  build-toolkit:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
      TOOLKIT_REPO: ghcr.io/${{github.repository}}/elemental-cli 
    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch --prune --unshallow
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build toolkit
        run: |
          make DOCKER_ARGS=--load build
          make DOCKER_ARGS=--push build

  build-matrix:
    needs:
      - detect
      - build-toolkit
    strategy:
      matrix:
        flavor: ${{fromJson(needs.detect.outputs.flavor)}}
      fail-fast: false
    uses: ./.github/workflows/build_and_test_x86.yaml
    with:
      flavor: ${{ matrix.flavor }}
