name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # undocumented OIDC support.
      contents: write
    env:
      COSIGN_EXPERIMENTAL: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version-file: go.mod
      - name: Set up cosign
        uses: sigstore/cosign-installer@v2.8.0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.ELEMENTAL_BOT_GITHUB_TOKEN }}

  release-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.ELEMENTAL_BOT_GITHUB_USERNAME }}
          password: ${{ secrets.ELEMENTAL_BOT_GITHUB_TOKEN }}
      - name: Build toolkit image
        run: |
          make TOOLKIT_REPO=ghcr.io/${{ github.workspace }}/${{ github.repository }}/elemental-cli VERSION=$(git describe --abbrev=0 --tags) build push-toolkit
          make PLATFORM=linux/arm64,linux/amd64 TOOLKIT_REPO=ghcr.io/${{ github.workspace }}/${{ github.repository }}/elemental-cli VERSION=latest build push-toolkit
      - name: Build green example
        run: |
          make FLAVOR=green REPO=ghcr.io/${{ github.workspace }}/${{ github.repository }}/elemental-${{ matrix.flavor}} VERSION=$(git describe --abbrev=0 --tags) build-os push-os
          make FLAVOR=tumbleweed REPO=ghcr.io/${{ github.workspace }}/${{ github.repository }}/elemental-${{ matrix.flavor}} VERSION=$(git describe --abbrev=0 --tags) build-os push-os
