name: resigner
on:
  workflow_dispatch:
    inputs:
      final-repo:
        required: false
        default: quay.io/costoolkit/releases-green
        type: string
        description: Repo to check artifacts for signatures
      cosign-repository:
        required: false
        default: raccos/releases-green
        type: string
        description: Repo that contains the signatures for the final_repo
      fulcio-url:
        required: false
        default: ""
        type: string
        description: Set a fulcio url for the signing part. LEave empty to use cosign default url..
      reference-id:
        required: false
        default: "repository.yaml"
        type: string
        description: Name of the repository.yaml that will be downloaded.
      cosign-version:
        required: false
        default: "v1.4.1"
        type: string
        description: Cosign version to install and use
concurrency:
  group: ci-sign-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  resign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC support
    env:
      FINAL_REPO: ${{ github.event.inputs.final-repo }}
      COSIGN_REPOSITORY: ${{ github.event.inputs.cosign-repository }}
      FULCIO_URL: ${{ github.event.inputs.fulcio-url }}
      REFERENCEID: ${{ github.event.inputs.reference-id }}
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: ${{ github.event.inputs.cosign-version }}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Resign
        run: |
          export PATH=$PATH:/usr/local/go/bin
          pushd ./.github
          go build -o resign resign.go
          popd
          sudo -E ./.github/resign
