{{ if ne .Values.codename "teal" }}
requires:
- name: "base"
  category: "distro"
  version: ">=0"
{{ else }}
image: {{.Values.tool_image}}
{{ end }}
prelude:
{{ if .Values.distribution }}
{{if eq .Values.distribution "opensuse" }}
- zypper in -y curl git && zypper install -y -t pattern devel_basis
{{else if eq .Values.distribution "fedora" }}
- dnf install -y curl git "@Development Tools"
{{else if eq .Values.distribution "ubuntu" }}
- apt-get update
- apt-get install -y build-essential curl git
{{end}}
{{end}}
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && \
  curl -L {{.Values.base_url}}/go$PACKAGE_VERSION.linux-{{.Values.golang_arch}}.tar.gz -o golang.tar.gz
{{ template "do_checksum" (dict "values" .Values "filename" "golang.tar.gz")}}

steps:
- tar -C /usr/local -xzf golang.tar.gz
