{{if eq .Values.codename "teal" }}
requires:
- name: "base"
  category: "distro"
  version: ">=0"

steps:
- mkdir -p /usr/share/elemental/selinux
- cp elemental.pp elemental.te /usr/share/elemental/selinux
{{end}}
